# Generated by Django 3.0.2 on 2020-03-26 14:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='state',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('confirmedCase', models.IntegerField(default=0, max_length=256)),
                ('inHospital', models.IntegerField(default=0, max_length=256)),
                ('deaths', models.IntegerField(default=0, max_length=256)),
                ('time', models.DateTimeField(default=datetime.datetime(2020, 3, 26, 14, 20, 24, 818731, tzinfo=utc))),
            ],
        ),
    ]
