# Generated by Django 3.0.2 on 2020-03-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state',
            old_name='confirmedCase',
            new_name='confirmedIndians',
        ),
        migrations.RemoveField(
            model_name='state',
            name='time',
        ),
        migrations.AddField(
            model_name='state',
            name='confirmedInternationals',
            field=models.IntegerField(default=0, max_length=256),
        ),
        migrations.AddField(
            model_name='state',
            name='cured',
            field=models.IntegerField(default=0, max_length=256),
        ),
    ]
