# Generated by Django 3.0.2 on 2020-05-11 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200328_1002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state',
            old_name='confirmedInternationals',
            new_name='active',
        ),
    ]
